relabel: []
admission:
  certManager:
    enabled: false
  secret:
    enabled: false
    caBundle: ''
    name: ''
  rules:
    - operations:
        - CREATE
        - UPDATE
      apiGroups:
        - ''
      apiVersions:
        - v1
      resources:
        - pods
  namespaceSelector: nil
log:
  format: text
  level: debug
replicaCount: 3
image:
  repository: ghcr.io/pdylanross/kube-resource-relabel-webhook
  pullPolicy: Always
  tag: 0.1.2
resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 128Mi
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
metrics:
  enabled: true
  serviceMonitor:
    enabled: false
    additionalLabels: {}
  listener:
    port: 8001
    host: 0.0.0.0
    tls:
      enabled: false
      secretName: ''
      certManager:
        enabled: false
        issuerName: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8443
nodeSelector: {}
tolerations: []
affinity: {}
