name: Setup Golang
description: Setup golang and get cached files
inputs:
  go-version:
    default: "1.21"
    description: The go version to use
    required: true
  cache:
    default: true
    description: if setup-go should cache
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}
        cache: ${{ inputs.cache }}