relabel:
  - name: "airflow-k8s-pod-operator-do-not-evict"
    conditions:
      - type: is-type
        value:
          version: v1
          kind: pod
      - type: has-label
        value:
          keys:
            - dag_id
    actions:
      - type: ensure-annotation
        value:
          karpenter.sh/do-not-evict: "true"