apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{- with .Values.relabel }}
  config.yaml: |
    relabel:
      {{- toYaml . | nindent 6 }}
  {{- end }}