apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - serve
            - --relabel-config-file=/etc/relabel/config.yaml
            - --webhook-port={{ .Values.service.port }}
            {{- if (eq .Values.metrics.enabled true) }}
            - --metrics-enabled
            - --metrics-port={{ .Values.metrics.listener.port }}
            {{- end }}
            {{- if .Values.admission.secret.enabled }}
            - --webhook-tls-cert-file=/etc/relabel/certs/tls.crt
            - --webhook-tls-key-file=/etc/relabel/certs/tls.key
            {{- end }}
            - --log-format={{ .Values.log.format }}
            - --log-level={{ .Values.log.level }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            {{- if (eq .Values.metrics.enabled true) }}
            - name: metrics
              containerPort: {{ .Values.metrics.listener.port }}
              protocol: TCP
            {{- end }}
          readinessProbe:
            httpGet:
              path: /livez
              port: https
              scheme: HTTPS
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/relabel
            {{- if .Values.admission.secret.enabled }}
            - name: cert
              mountPath: /etc/relabel/certs
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "chart.fullname" .}}-config
        {{- if .Values.admission.secret.enabled }}
        - name: cert
          secret:
            secretName: {{ .Values.admission.secret.name }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
