{{- if and (eq .Values.metrics.enabled true) (eq .Values.metrics.serviceMonitor.create true) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    {{- .Values.metrics.serviceMonitor.additionalLabels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 4 }}
  endpoints:
    - port: metrics
{{- end }}