apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "chart.fullname" . }}
  {{- if .Values.admission.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace}}/{{ include "chart.fullname" . }}
  {{- end }}
webhooks:
  - name: v1.kube-resource-relabel-webhook.dev
    admissionReviewVersions: ["v1beta1", "v1"]
    sideEffects: None
    clientConfig:
      {{- if .Values.admission.secret.enabled }}
      caBundle: "{{ .Values.admission.secret.caBundle }}"
      {{- end }}
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "chart.fullname" . }}
        path: /webhook/mutate
        port: {{ .Values.service.port }}
    objectSelector:
      # app.kubernetes.io/name: {{ include "chart.name" . }}
      # app.kubernetes.io/instance: {{ .Release.Name }}
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - {{ include "chart.name" . }}
        - key: app.kubernetes.io/instance
          operator: NotIn
          values:
            - {{ .Release.Name }}
    rules:
      {{ toYaml .Values.admission.rules | nindent 6}}