relabel:
  - name: "airflow-k8s-pod-operator-do-not-evict"
    conditions:
      - type: is-type
        value:
          kind: pod
          version: v1
      - type: has-label
        value:
          keys:
            - dag_id
    actions:
      - type: ensure-annotation
        value:
          karpenter.sh/do-not-evict: "true"
  - name: "cleanup-fluentd-labels"
    conditions:
      - type: is-type
        value:
          kind: pod
          version: v1
      - type: has-annotation
        value:
          match:
            fluentd.active: "true"
    actions:
      - type: ensure-label
        value:
          fluentd.active: "true"
  - name: "add-test2-label"
    conditions:
      - type: is-type
        value:
          kind: pod
          version: v1
      - type: has-annotation
        value:
          keys:
            - test2
    actions:
      - type: ensure-label
        value:
          test2: "value"
  - name: "nginx ingress ensure default backend"
    conditions:
      - type: is-type
        value:
          kind: ingress
          version: v1
          group: networking.k8s.io
    actions:
      - type: ensure-annotation
        value:
          nginx.ingress.kubernetes.io/default-backend: some-svc

replicaCount: 1
fullnameOverride: kube-resource-relabel-webhook

admission:
  rules:
    - operations:
        - CREATE
        - UPDATE
      apiGroups:
        - ''
      apiVersions:
        - v1
      resources:
        - pods
    - operations:
        - CREATE
        - UPDATE
      apiGroups:
        - 'networking.k8s.io'
      apiVersions:
        - v1
      resources:
        - ingresses