baseURL = 'https://pdylanross.github.io/kube-resource-relabel-webhook/'
languageCode = 'en-us'
title = 'kube-resource-relabel-webhook docs'
theme = "hugo-geekdoc"

pluralizeListTitles = false
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true
enableRobotsTXT = true

defaultContentLanguage = "en"

[languages.en]
languageName = "English"
contentDir = "content/en"
weight = 10


[markup]
    [markup.goldmark.renderer]
    # Needed for mermaid shortcode
        unsafe = true
    [markup.tableOfContents]
        startLevel = 1
        endLevel = 9
[taxonomies]
tag = "tags"

[params]
    # (Optional, default none) Set source repository location. Used for 'Edit page' links.
    # You can also specify this parameter per page in front matter.
    geekdocRepo = "https://github.com/pdylanross/kube-resource-relabel-webhook/tree/main"

    # (Optional, default none) Enable 'Edit page' links. Requires 'geekdocRepo' param
    # and the path must point to the parent directory of the 'content' folder.
    # You can also specify this parameter per page in front matter.
    geekdocEditPath = "doc"

