baseURL = 'https://pdylanross.github.io/kube-resource-relabel-webhook/'
languageCode = 'en-us'
title = 'kube-resource-relabel-webhook docs'
theme = "hugo-geekdoc"

pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true
enableRobotsTXT = true

[markup]
    [markup.goldmark.renderer]
    # Needed for mermaid shortcode
        unsafe = true
    [markup.tableOfContents]
        startLevel = 1
        endLevel = 9

[params]
    # (Optional, default none) Set source repository location. Used for 'Edit page' links.
    # You can also specify this parameter per page in front matter.
    geekdocRepo = "https://github.com/pdylanross/kube-resource-relabel-webhook"

    # (Optional, default none) Enable 'Edit page' links. Requires 'geekdocRepo' param
    # and the path must point to the parent directory of the 'content' folder.
    # You can also specify this parameter per page in front matter.
    geekdocEditPath = "doc"

[params.docs]
darkMode=true

repoURL="https://github.com/pdylanross/kube-resource-relabel-webhook"
repoBranch="main"
editPage=true
lastMod=true
lastModRelative=true


[menu]
[[menu.primary]]
name  = "Docs"
url = "docs/"
identifier = "docs"
weight = 10