on:
  push:

name: CI
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup-golang
        with:
          cache: false
      - name: lint
        uses: ./.github/actions/lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup-golang
      - name: unit-test
        run: make unit-test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: build
        run: make build

  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Helm Lint
        run: helm lint ./chart

  release-dev-container:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - lint
      - unit-test
      - build
    steps:
      - uses: actions/checkout@v4
      - name: Release Container
        uses: ./.github/actions/release
        with:
          tag: ${{ github.sha }}

  release-please:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - release-dev-container
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          package-name: github.com/pdylanross/kube-resource-relabel-webhook
          command: manifest
          token: ${{ secrets.RELEASE_PLEASE_PAT }}