on:
  push:
    branches-ignore:
      - docs
      - gh-pages

name: CI
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup-golang
        with:
          cache: false
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup-golang
      - name: unit-test
        run: make unit-test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Get Date
        id: date
        run: |
          echo "current=$(date --rfc-3339=seconds)" >> "$GITHUB_OUTPUT"
      - name: Test Docker Build
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ghcr.io/pdylanross/kube-resource-relabel-webhook:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=ci-${{ github.sha }}
            COMMIT_HASH=${{  github.sha }}
            BUILD_TIMESTAMP=${{ steps.date.outputs.current }}

  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Helm Lint
        run: helm lint ./chart

  release-dev-container:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - lint
      - lint-chart
      - unit-test
      - build
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Get Date
        id: date
        run: |
          echo "current=$(date --rfc-3339=seconds)" >> "$GITHUB_OUTPUT"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/pdylanross/kube-resource-relabel-webhook:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=ci-${{ github.sha }}
            COMMIT_HASH=${{  github.sha }}
            BUILD_TIMESTAMP=${{ steps.date.outputs.current }}

  release-please:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - release-dev-container
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          package-name: github.com/pdylanross/kube-resource-relabel-webhook
          command: manifest
          token: ${{ secrets.RELEASE_PLEASE_PAT }}