on:
  push:

name: CI
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup-golang
        with:
          cache: false
      - name: lint
        uses: ./.github/actions/lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup-golang
      - name: unit-test
        uses: ./.github/actions/unit-test