on:
  pull_request:

name: PR

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: helm/kind-action@v1.8.0
        with:
          install_only: true
      - uses: azure/setup-helm@v3
      - name: Setup
        uses: ./.github/actions/setup-golang
      - name: unit-test
        run: make integration-test