name: release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: main

      - uses: actions/checkout@v4
        with:
          path: pages
          ref: gh-pages

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}


      - name: Get Date
        id: date
        run: |
          echo "current=$(date --rfc-3339=seconds)" >> "$GITHUB_OUTPUT"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/pdylanross/kube-resource-relabel-webhook:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ github.ref_name }}
            COMMIT_HASH=${{  github.sha }}
            BUILD_TIMESTAMP=${{ steps.date.outputs.current }}

      - name: Configure Git
        working-directory: ./pages
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Package helm chart
        working-directory: ./
        run: |
          helm package ./main/chart -d ./pages/helm-charts

      - name: Setup helm index
        working-directory: ./pages/helm-charts
        run: |
          helm repo index --url https://pdylanross.github.io/kube-resource-relabel-webhook .

      - name: Commit chart repo
        working-directory: ./pages
        run: |
          git add -A ./
          git commit -am "release: ${{ github.ref_name }}"
          git push 
