name: release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: main

      - uses: actions/checkout@v4
        with:
          path: pages
          ref: gh-pages

      - uses: ./main/.github/actions/release
        name: Publish Container
        with:
          tag: ${{ github.ref_name }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Package helm chart
        run: |
          helm package ./main/chart -d ./gh-pages/helm-charts

      - name: Setup helm index
        working-directory: ./gh-pages/helm-charts
        run: |
          helm repo index --url https://pdylanross.github.io/kube-resource-relabel-webhook .

      - name: Commit chart repo
        working-directory: ./gh-pages
        run: |
          git add -A ./
          git commit -am "release: ${{ github.ref_name }}"
          git push 
