name: release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: main

      - uses: actions/checkout@v4
        with:
          path: pages
          ref: gh-pages

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Container
        working-directory: ./main
        run: make build

      - name: Publish Tag
        working-directory: ./main
        run: ./ci/publish.sh ${{ github.ref_name }}

      - name: Configure Git
        working-directory: ./pages
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Package helm chart
        working-directory: ./
        run: |
          helm package ./main/chart -d ./pages/helm-charts

      - name: Setup helm index
        working-directory: ./gh-pages/helm-charts
        run: |
          helm repo index --url https://pdylanross.github.io/kube-resource-relabel-webhook .

      - name: Commit chart repo
        working-directory: ./gh-pages
        run: |
          git add -A ./
          git commit -am "release: ${{ github.ref_name }}"
          git push 
