name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Get Date
        id: date
        run: |
          echo "current=$(date --rfc-3339=seconds)" >> "$GITHUB_OUTPUT"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/pdylanross/kube-resource-relabel-webhook:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ github.ref_name }}
            COMMIT_HASH=${{  github.sha }}
            BUILD_TIMESTAMP=${{ steps.date.outputs.current }}

  build-docs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          path: main

      - uses: actions/checkout@v4
        with:
          path: pages
          ref: gh-pages

      - name: Setup Golang
        uses: ./main/.github/actions/setup-golang

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.118.2"
          extended: true

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        working-directory: ./pages
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Create pages deploy dir
        working-directory: ./pages
        run: |
          mkdir -p ./public/helm-charts

      - name: Package helm chart
        working-directory: ./
        run: |
          helm package ./main/chart -d ./pages/helm-charts


      - name: Setup helm index
        working-directory: ./pages/helm-charts
        run: |
          helm repo index --url https://pdylanross.github.io/kube-resource-relabel-webhook .
          cp -r . ../public/helm-charts

      - name: Setup Doc Site Deps
        working-directory: ./main
        run: make doc-setup

      - name: Build Doc Site
        working-directory: ./main/doc
        run: hugo -v --destination ../../pages/public --gc --baseURL "${{ steps.pages.outputs.base_url }}"

      - name: Commit chart repo
        working-directory: ./pages
        run: |
          git add -A ./
          git commit -am "release: ${{ github.ref_name }}"
          git push

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./pages/public

  deploy-docs:
    permissions: write-all
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2